export enum LanguageCode {
	GlobalEnglish = 'en',
	AustralianEnglish = 'en_au',
	BritishEnglish = 'en_uk',
	USEnglish = 'en_us',
	Spanish = 'es',
	French = 'fr',
	German = 'de',
	Italian = 'it',
	Portuguese = 'pt',
	Dutch = 'nl',
	Hindi = 'hi',
	Japanese = 'ja',
	Chinese = 'zh',
	Finnish = 'fi',
	Korean = 'ko',
	Polish = 'pl',
	Russian = 'ru',
	Turkish = 'tr',
	Ukrainian = 'uk',
	Vietnamese = 'vi',
}
